version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Node.js dependencies...
      - npm install
      - npm install express

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 430118853571.dkr.ecr.ap-south-1.amazonaws.com
      - echo  $REPOSITORY_URI

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
      - echo Writing image details to output file...

artifacts:
  files:
    - imageDetail.txt
